name: EAS Update on Push

on:
  push:
    branches:
      - main  
      

jobs:
  eas-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Run EAS Update
        run: eas update --auto
